permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate
        run: |
          mkdir -p ./.build/docc && \
          xcodebuild clean docbuild \
            -scheme "Trap" \
            -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" \
            -derivedDataPath "./.build/docc"
          $(xcrun --find docc) \
            process-archive transform-for-static-hosting \
            .build/docc/Build/Products/Debug-iphonesimulator/Trap.doccarchive \
            --output-path public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
